#!/usr/bin/python

import user
import dexcom_reader
from dexcom_reader import readdata
from pprint import pformat, pprint
import xml.etree.ElementTree as etree

def main( ):
  Dexcom = readdata.Dexcom
  device = Dexcom.FindDevice()
  if not device:
    sys.stderr.write('Could not find Dexcom G4 Receiver!\n')
    sys.exit(1)
  else:
    print device
    dex = Dexcom(device)
    print ('Found %s S/N: %s'
           % (dex.GetFirmwareHeader().get('ProductName'),
              dex.ReadManufacturingData().get('SerialNumber')))
    xml = dex.ReadManufacturingData()
    for x in list(xml):
      print x
    # root.append(xml)
    print 
    print 'Receiver Firmware: %s' % etree.tostring(dex.GetFirmwareHeader( ))
    print 'Receiver Manufacturer: %s' % etree.tostring(xml)
    print 'Transmitter paired: %s' % dex.ReadTransmitterId()
    print 'Battery Status: %s (%d%%)' % (dex.ReadBatteryState(),
                                         dex.ReadBatteryLevel())

if __name__ == '__main__':
  main( )
